version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: symfony_php
    working_dir: /var/www/kodano-task
    volumes:
      - ./kodano-task:/var/www/kodano-task
    depends_on:
      - mysql
    networks:
      - symfony_network

  mysql:
    image: mysql:8.0
    container_name: symfony_mysql
    environment:
      MYSQL_DATABASE: app
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    ports:
      - "33061:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - symfony_network

  nginx:
    image: nginx:alpine
    container_name: symfony_nginx
    ports:
      - "8000:80"
    volumes:
      - ./kodano-task:/var/www/kodano-task
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - php
    networks:
      - symfony_network

networks:
  symfony_network:
    driver: bridge

volumes:
  mysql_data: 